# -*- coding: utf-8 -*-
"""QuizGame.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hPGzxxC0SOpYzuicTGPwz9zOh2PhAlws
"""

print("WELCOME TO COMPUTER QUIZ!!")
playing = input("DO YOU WANT TO PLAY? ").lower()
if playing != "yes":
    quit()
print("OKAY LET'S PLAY :")
score = 0
answer = input("WHAT DOES CPU STANDS FOR? ").lower()
if answer == "central processing unit":
      print("correct!!")
      score += 1
else:
      print("incorrect!!")

answer = input("WHAT DOES RAM STANDS FOR? ").lower()
if answer == "random access memory":
      print("correct!!")
      score += 1
else:
      print("incorrect!!")

answer = input("WHAT DOES GPU STANDS FOR? ").lower()
if answer == "graphics processing unit":
      print("correct!!")
      score += 1
else:
      print("incorrect!!")

print("YOU GOT " + str(score) + " ANSWERS CORRECT.")
print("YOU GOT " + str((score/3)*100)+"%")